---
- name: deploy mezzanine on vagrant
  hosts: web
  vars_files:
    - secrets.yml
  roles:
    - role: aptsource
    - role: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"
    - role: mezzanine
      live_hostname: 192.168.56.10.xip.io
      domains:
        - 192.168.56.10.xip.io
        - www.192.168.56.10.xip.io
